version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: symfony
    depends_on:
      - 'db'
    ports:
      - 81:80
    volumes:
      - .:/app/

  db:
    container_name: db
    image: postgres:10-alpine
    ports:
      - '15432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
